<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rooms = [
            [
                'name' => 'California Fitness & Yoga',
                'address' => 'Số 126 Hùng Vương, P.12, Q.5, Tp. Hồ Chí Minh, Việt Nam',
                'price' => 400000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 0,
                'sauna' => 0,
                'coach' => 0,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Nshape Fitness',
                'address' => '16 P.Hàm Long, Phan Chu Trinh, Hoàn Kiếm, Hà Nội',
                'price' => 500000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 1,
                'parking' => 1,
                'sauna' => 0,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Saiyan Fitness',
                'address' => '219 P. Trung Kính, Yên Hoà, Cầu Giấy, Hà Nội',
                'price' => 750000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 1,
                'sauna' => 0,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Fuel Fitness',
                'address' => '99 P. Mạc Thái Tổ, Yên Hoà, Cầu Giấy, Hà Nội',
                'price' => 400000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 1,
                'sauna' => 0,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Elite Fitness',
                'address' => 'Tầng 6, Vinhomes 54A Nguyễn Chí Thanh, Ngọc Khánh, Ba Đình, Hà Nội',
                'price' => 800000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 1,
                'sauna' => 1,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Fitness World',
                'address' => '29 P. Hoàng Đạo Thúy, Trung Hoà, Cầu Giấy, Hà Nội',
                'price' => 625000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 0,
                'sauna' => 1,
                'coach' => 0,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'XFitness',
                'address' => '2QP5+MX3, P. Hàm Nghi, Cầu Diễn, Từ Liêm, Hà Nội',
                'price' => 700000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 0,
                'sauna' => 1,
                'coach' => 0,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'MD Fitness',
                'address' => '194 Thái Thịnh, Cây Xăng Dầu Thái Thịnh, Hà Nội',
                'price' => 550000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 1,
                'parking' => 1,
                'sauna' => 1,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Level Fitness Center',
                'address' => 'Tầng 6, The Nine Tower – 09 Phạm Văn Đồng, Cầu Giấy, HN',
                'price' => 1200000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 1,
                'parking' => 1,
                'sauna' => 1,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'Nuke Fitness',
                'address' => 'tầng 2, B14, phạm ngọc thạch, kim liên, đống đa Hà Nội',
                'price' => 420000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 1,
                'sauna' => 0,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ],
            [
                'name' => 'HPC Gym',
                'address' => 'Tầng 2, số 23 Ngõ 28 Nguyên Hồng, Đống Đa (Ngõ 97 Nguyễn Chí Thanh), Hà Nội',
                'price' => 635000,
                'owner_id' => 4,
                'numberOfUsers' => 0,
                'rating' => null,
                'pool' => 0,
                'parking' => 1,
                'sauna' => 0,
                'coach' => 1,
                'active' => 1,
                'is_admin_approved' => 1,
            ]
        ];

        DB::table('rooms')->insert($rooms);
    }
}
